install(DIRECTORY org.blossomos.blossomuilight.desktop
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/look-and-feel)

install(DIRECTORY org.blossomos.blossomuidark.desktop
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/look-and-feel)

install(DIRECTORY org.blossomos.blossomuidarkoled.desktop
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/look-and-feel)
