[Icon Theme]
Name=BlossomUI Icons
Comment=BlossomOS icon theme
Inherits=breeze,hicolor
Example=folder
FollowsColorScheme=true
DisplayDepth=32
KDE-Extensions=.svgz,svg

DesktopDefault=48
ToolbarDefault=22
MainToolbarDefault=22
SmallDefault=16
PanelDefault=48
DialogDefault=32

Directories=animations/16,animations/22,apps/16,apps/22,apps/24,apps/32,apps/48,apps/64,apps/symbolic,actions/16,actions/22,actions/24,actions/symbolic,categories/16,categories/22,categories/symbolic,devices/16,devices/22,devices/symbolic,emblems/symbolic,emotes/symbolic,mimetypes/16,mimetypes/22,mimetypes/24,mimetypes/32,mimetypes/64,mimetypes/symbolic,places/16,places/22,places/32,places/48,places/96,places/64,status/16,status/22,status/24,status/32,status/48,status/64,status/symbolic

ScaledDirectories=mimetypes/16@2x,mimetypes/16@3x,mimetypes/22@2x,mimetypes/22@3x,mimetypes/24@2x,mimetypes/24@3x,places/16@2x,places/16@3x,places/22@2x,places/22@3x

[animations/16]
Context=Animations
Size=16
Type=Fixed

[animations/22]
Context=Animations
Size=22
Type=Fixed

[apps/16]
Context=Applications
Size=16
Type=Fixed

[apps/22]
Context=Applications
Size=22
Type=Fixed

[apps/24]
Context=Applications
Size=24
Type=Fixed

[apps/32]
Context=Applications
Size=32
Type=Fixed

[apps/48]
Context=Applications
Size=48
Type=Fixed

[apps/64]
Context=Applications
Size=64
Type=Fixed

[categories/16]
Context=Categories
Size=16
Type=Fixed

[categories/22]
Context=Categories
Size=22
Type=Fixed

[mimetypes/16]
Context=MimeTypes
Size=16
Type=Fixed

[mimetypes/16@2x]
Context=MimeTypes
Size=16
Scale=2
Type=Fixed

[mimetypes/16@3x]
Context=MimeTypes
Size=16
Scale=3
Type=Fixed

[mimetypes/22]
Context=MimeTypes
Size=22
Type=Fixed

[mimetypes/22@2x]
Context=MimeTypes
Size=22
Scale=2
Type=Fixed

[mimetypes/22@3x]
Context=MimeTypes
Size=22
Scale=3
Type=Fixed

[mimetypes/24]
Context=MimeTypes
Size=24
Type=Fixed

[mimetypes/24@2x]
Context=MimeTypes
Size=24
Scale=2
Type=Fixed

[mimetypes/24@3x]
Context=MimeTypes
Size=24
Scale=3
Type=Fixed

[mimetypes/32]
Context=MimeTypes
Size=32
Type=Fixed

[mimetypes/64]
Context=MimeTypes
Size=64
Type=Fixed

[places/16]
Size=16
Context=Places
Type=Fixed
MinSize=16

[places/16@2x]
Size=16
Scale=2
Context=Places
Type=Fixed
MinSize=16

[places/16@3x]
Size=16
Scale=3
Context=Places
Type=Fixed
MinSize=16

[places/22]
Size=22
Context=Places
Type=Fixed

[places/22@2x]
Size=22
Scale=2
Context=Places
Type=Fixed

[places/22@3x]
Size=22
Scale=3
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[places/64]
Size=64
Context=Places
Type=Fixed

[places/96]
Size=96
Context=Places
Type=Scalable
MinSize=96
MaxSize=256

[actions/16]
Context=Actions
Size=16
Type=Fixed

[actions/22]
Context=Actions
Size=22
Type=Fixed

[actions/24]
Context=Actions
Size=24
Type=Fixed


[status/16]
Context=Status
Size=16
Type=Fixed

[status/22]
Context=Status
Size=22
Type=Fixed

[status/24]
Context=Status
Size=24
Type=Fixed

[status/32]
Context=Status
Size=32
Type=Fixed

[status/48]
Context=Status
Size=48
Type=Fixed

[status/64]
Context=Status
Size=64
Type=Fixed

[actions/symbolic]
Context=Actions
Size=16
Type=Fixed

[apps/symbolic]
Context=Applications
Size=16
Type=Fixed

[devices/symbolic]
Context=Devices
Size=16
Type=Fixed

[emblems/symbolic]
Context=Emblems
Size=16
Type=Fixed

[status/symbolic]
Context=Status
Size=16
Type=Fixed

[categories/symbolic]
Context=Categories
Size=16
Type=Fixed

[devices/16]
Context=Devices
Size=16
Type=Fixed

[devices/22]
Context=Devices
Size=22
Type=Fixed

[emotes/symbolic]
Context=Emotes
Size=16
Type=Fixed

[mimetypes/symbolic]
Context=MimeTypes
Size=16
Type=Fixed
