install(DIRECTORY org.blossomos.ui.light.desktop
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/look-and-feel)

install(DIRECTORY org.blossomos.ui.dark.desktop
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/look-and-feel)

install(DIRECTORY org.blossomos.ui.darkoled.desktop
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/look-and-feel)
