#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later

import re
import sys
from pathlib import Path

GENERATED_MARKER = (
    "// GENERATED by generate-wrappers.py — do not edit, regenerate instead."
)

WRAPPER_TEMPLATE = """{marker}
// SPDX-License-Identifier: GPL-2.0-or-later

import org.kde.desktop as Desktop

Desktop.{name} {{}}
"""

MODULE_NAME = "org.blossomos.style"

DEFAULT_QMLDIR_CANDIDATES = [
    "/usr/lib64/qt6/qml/org/kde/desktop/qmldir",
    "/usr/lib/qt6/qml/org/kde/desktop/qmldir",
    "/usr/lib/x86_64-linux-gnu/qt6/qml/org/kde/desktop/qmldir",
]


def find_source_qmldir() -> Path:
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    for candidate in DEFAULT_QMLDIR_CANDIDATES:
        if Path(candidate).exists():
            return Path(candidate)
    sys.exit("error: org.kde.desktop qmldir not found; pass its path as argument")


def parse_types(qmldir: Path) -> list[str]:
    types = []
    for line in qmldir.read_text().splitlines():
        # public type entries look like: "Button 1.0 Button.qml"
        match = re.fullmatch(r"(\w+) [\d.]+ \1\.qml", line.strip())
        if match:
            types.append(match.group(1))
    if not types:
        sys.exit(f"error: no type entries found in {qmldir}")
    return types


def main() -> None:
    style_dir = Path(__file__).resolve().parent / "style"
    source_qmldir = find_source_qmldir()
    types = parse_types(source_qmldir)

    generated, kept = [], []
    for name in types:
        target = style_dir / f"{name}.qml"
        if target.exists() and GENERATED_MARKER not in target.read_text():
            kept.append(name)
            continue
        target.write_text(WRAPPER_TEMPLATE.format(marker=GENERATED_MARKER, name=name))
        generated.append(name)

    # Remove stale wrappers for types that no longer exist upstream.
    removed = []
    for qml in style_dir.glob("*.qml"):
        if qml.stem not in types and GENERATED_MARKER in qml.read_text():
            qml.unlink()
            removed.append(qml.stem)

    qmldir_lines = [f"module {MODULE_NAME}"]
    qmldir_lines += [f"{name} 1.0 {name}.qml" for name in sorted(types)]
    (style_dir / "qmldir").write_text("\n".join(qmldir_lines) + "\n")

    print(f"source:    {source_qmldir}")
    print(f"generated: {len(generated)} wrappers")
    print(f"kept:      {len(kept)} hand-written ({', '.join(kept)})")
    if removed:
        print(f"removed:   {len(removed)} stale ({', '.join(removed)})")


if __name__ == "__main__":
    main()
