if(EXISTS "${CMAKE_SOURCE_DIR}/../colors.json")
    file(READ "${CMAKE_SOURCE_DIR}/../colors.json" _bui_json)
elseif(EXISTS "${CMAKE_SOURCE_DIR}/colors.json")
    file(READ "${CMAKE_SOURCE_DIR}/colors.json" _bui_json)
else()
    message(FATAL_ERROR "colors.json not found at ${CMAKE_SOURCE_DIR}/../ or ${CMAKE_SOURCE_DIR}/")
endif()

foreach(_bui_group IN ITEMS neutral primary secondary tertiary quaternary red cyan)
    string(JSON _bui_n LENGTH "${_bui_json}" "${_bui_group}")
    string(TOUPPER "${_bui_group}" _bui_GROUP)
    math(EXPR _bui_last "${_bui_n} - 1")
    foreach(_bui_i RANGE ${_bui_last})
        string(JSON _bui_step MEMBER "${_bui_json}" "${_bui_group}" ${_bui_i})
        string(JSON _bui_hex  GET    "${_bui_json}" "${_bui_group}" "${_bui_step}")
        string(REPLACE "#" "" _bui_hx "${_bui_hex}")
        string(SUBSTRING "${_bui_hx}" 0 2 _bui_hr)
        string(SUBSTRING "${_bui_hx}" 2 2 _bui_hg)
        string(SUBSTRING "${_bui_hx}" 4 2 _bui_hb)
        math(EXPR _bui_r "0x${_bui_hr}")
        math(EXPR _bui_g "0x${_bui_hg}")
        math(EXPR _bui_b "0x${_bui_hb}")
        set(${_bui_GROUP}_${_bui_step}_RGB "${_bui_r},${_bui_g},${_bui_b}")
        string(TOLOWER "${_bui_hx}" _bui_hx_lower)
        set(${_bui_GROUP}_${_bui_step}_HEX "#${_bui_hx_lower}")
    endforeach()
endforeach()
